set_property SRC_FILE_INFO {cfile:/home/sdu/Documents/embeddedSystems/project/miniproject/vivado/ArmNet/ArmNet.srcs/constrs_1/new/ultra96_v2_ai_constraints.xdc rfile:../../../ArmNet.srcs/constrs_1/new/ultra96_v2_ai_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D7 [get_ports led_ctrl1_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports led_ctrl2_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports led_ctrl3_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports led_ctrl4_0]
